language: cpp
sudo: required
dist: xenial

compiler:
 - gcc

os:
- linux

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libssl-dev libconfig-dev libnl-3-dev libnl-genl-3-dev; fi

script: make && make test
