language: cpp
sudo: required
dist: xenial

compiler:
 - gcc

os:
- linux

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxml2-dev; fi

script: make && make test
