version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install deps
          command: apt-get update && apt-get install -y gcc make cmake pkg-config libssl-dev libconfig-dev libnl-3-dev libnl-genl-3-dev
      - run:
          name: build
          command: make && make test
