#!/bin/bash
#
# Init for authsae VM.
#
# This gets execed by the VM's init once the parent directory is
# mounted under /local.
#
dmesg -n 1
cd /local/tests
echo "--- begin tests ---"
# ./run_tests.sh
./test001.sh
echo "--- end tests ---"
poweroff
